{
 "title": "New dashboard Copy",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "\"/\" Endpoint Request Latency Percentile",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Seconds" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(request_latency_seconds_bucket{app_name=\"metrics_app\",endpoint=\"/\"}[5m])) by (le))",
     "legendFormat": "0.5"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(request_latency_seconds_bucket{app_name=\"metrics_app\",endpoint=\"/\"}[5m])) by (le))",
     "legendFormat": "0.95"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(request_latency_seconds_bucket{app_name=\"metrics_app\",endpoint=\"/\"}[5m])) by (le))",
     "legendFormat": "0.90"
    }
   ]
  },
  {
   "title": "\"/flaky\" Endpoint Status Codes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(request_count{app_name=\"metrics_app\",endpoint=\"/flaky\"}[5m])",
     "legendFormat": "{{http_status}}"
    }
   ]
  },
  {
   "title": "\"/slow\" Endpoint Request Latency Percentile",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "Seconds" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(request_latency_seconds_bucket{app_name=\"metrics_app\",endpoint=\"/slow\"}[5m])) by (le))",
     "legendFormat": "0.95"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(request_latency_seconds_bucket{app_name=\"metrics_app\",endpoint=\"/slow\"}[5m])) by (le))",
     "legendFormat": "0.90"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(request_latency_seconds_bucket{app_name=\"metrics_app\",endpoint=\"/slow\"}[5m])) by (le))",
     "legendFormat": "0.5"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(request_latency_seconds_bucket{app_name=\"metrics_app\",endpoint=\"/slow\"}[5m])) by (le))",
     "legendFormat": "0.99"
    }
   ]
  },
  {
   "title": "\"/flaky\" Endpoint Heatmap",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "rate(request_latency_seconds_bucket{app_name=\"metrics_app\",endpoint=\"/slow\"}[5m])",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}